class JailAi < Formula
  desc "Rust-based jail wrapper for sandboxing AI agents using podman or apple/container"
  homepage "https://github.com/cyrinux/jail-ai"
  license any_of: ["MIT", "Apache-2.0"]
  head "https://github.com/cyrinux/jail-ai.git", branch: "main"

  # Stable release bottles are generated by CI (see .github/workflows/release.yml)
  # The sha256 values below are placeholders; they are replaced by the release workflow.
  stable do
    url "https://github.com/cyrinux/jail-ai/archive/refs/tags/v0.49.0.tar.gz"
    sha256 :no_check
    version "0.49.0"
  end

  bottle do
    root_url "https://github.com/cyrinux/jail-ai/releases/download/v#{version}"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "PLACEHOLDER_ARM64_SEQUOIA"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "PLACEHOLDER_ARM64_SONOMA"
    sha256 cellar: :any_skip_relocation, ventura:       "PLACEHOLDER_VENTURA"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "PLACEHOLDER_X86_64_LINUX"
  end

  depends_on "rust" => :build

  # Runtime: one of podman (available on all platforms via brew) or apple/container (macOS only)
  depends_on "podman" => :recommended
  # apple/container is a cask; users install it separately if they prefer it over podman.
  # We don't add it here as a hard dependency because it is a cask and macOS-only.

  def install
    system "cargo", "install", *std_cargo_args

    # Install shell completions
    generate_completions_from_executable(bin/"jail-ai", "completions")

    # Install man page if present
    man1.install "docs/jail-ai.1" if File.exist?("docs/jail-ai.1")
  end

  def caveats
    <<~EOS
      jail-ai sandboxes AI agents in containers. It supports two container backends:

        1. podman  – works on both Linux and macOS (default, installed via Homebrew)
        2. apple/container – macOS-only; install from https://github.com/apple/container
                             or: brew install --cask apple/container/container

      jail-ai automatically selects the best available backend:
        • macOS: prefers apple/container when installed, falls back to podman
        • Linux: always uses podman

      QUICK START
      -----------
        # Run Claude Code sandboxed in the current directory
        jail-ai claude

        # Run GitHub Copilot (mount credentials first)
        jail-ai copilot --copilot-dir

        # Run Gemini CLI
        jail-ai gemini --gemini-dir

      FIRST RUN
      ---------
      On first use jail-ai automatically builds a layered container image for your
      project type (Rust, Go, Node.js, Python, …). This may take a few minutes.
      The embedded Containerfile is written to:
        ~/.config/jail-ai/Containerfile

      Edit that file to customise the base image for your projects.

      NOTE: eBPF-based host blocking is a Linux-only feature and is silently
      disabled on macOS. Network isolation still applies.
    EOS
  end

  test do
    assert_match "jail-ai", shell_output("#{bin}/jail-ai --help")
    assert_match version.to_s, shell_output("#{bin}/jail-ai --version")
  end
end
